---

version: "3.7"

networks:
  smartshop_services:

services:
  api_go_template:
    image: api_go_template
    networks:
      smartshop_services:
        aliases:
          - api-go-template-ecs.app.internal
